### PR TITLE
Updated tests on web docs . 

### PR DESCRIPTION
**Pull request by sambhavnoobcoder**
added the updated tests on the web documentation of pecan . fixes the issue #153 .Pr and changes made adhering to the guidelines of contribution for the repository .

### CODE REVIEW

**Comment by sambhavnoobcoder** [comment]
@ryanpetrello  @mgorny  @markmcclain  @maintainers could you kindly look into this pr and merge the same ?

**Comment by ryanpetrello** [comment]
Thank you (this was merged as https://github.com/pecan/pecan/pull/155)

**Comment by sambhavnoobcoder** [comment]
by the way , @ryanpetrello could you tell me what changes were made different from my original pr ? or what improvements were required in my pr for it to be merged as is ? your insights would be very helpful.

**Comment by ryanpetrello** [comment]
Hey @sambhavnoobcoder,

I took your MR and just condensed it a bit to just suggest people use `tox` by default.

Also, I included you as a co-author so you're credited as an author:

https://github.com/pecan/pecan/pull/155/commits/3de40ff924bb525408b3f57f40ef517d8aeee25b

Thanks for working on this doc issue.

**Comment by sambhavnoobcoder** [comment]
okay got it . glad to work on the repo . I'll look forward to working on more issues in the organisation .

**Pull request closed without merging**
